// load top news
export const LOAD_NEWS_IN_START = "LOAD_NEWS_IN_START";
export const LOAD_NEWS_IN_SUCCESS = "LOAD_NEWS_IN_SUCCESS";
export const LOAD_NEWS_IN_FAIL = "LOAD_NEWS_IN_FAIL";


export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";

// load politics news


export const LOAD_POLITICS_IN_START = "LOAD_POLITICS_IN_START";
export const LOAD_POLITICS_IN_SUCCESS = "LOAD_POLITICS_IN_SUCCESS";
export const LOAD_POLITICS_IN_FAIL = "LOAD_POLITICS_IN_FAIL";


export const LOAD_ENT_IN_START = "LOAD_ENT_IN_START";
export const LOAD_ENT_IN_SUCCESS = "LOAD_ENT_IN_SUCCESS";
export const LOAD_ENT_IN_FAIL = "LOAD_ENT_IN_FAIL";


export const LOAD_SPORTS_IN_START = "LOAD_SPORTS_IN_START";
export const LOAD_SPORTS_IN_SUCCESS = "LOAD_SPORTS_IN_SUCCESS";
export const LOAD_SPORTS_IN_FAIL = "LOAD_SPORTS_IN_FAIL";


export const LOAD_FINANCE_IN_START = "LOAD_FINANCE_IN_START";
export const LOAD_FINANCE_IN_SUCCESS = "LOAD_FINANCE_IN_SUCCESS";
export const LOAD_FINANCE_IN_FAIL = "LOAD_FINANCE_IN_FAIL";




export const LOAD_TECHNOLOGY_IN_START = "LOAD_TECHNOLOGY_IN_START";
export const LOAD_TECHNOLOGY_IN_SUCCESS = "LOAD_TECHNOLOGY_IN_SUCCESS";
export const LOAD_TECHNOLOGY_IN_FAIL = "LOAD_TECHNOLOGY_IN_FAIL";